// <auto-generated />
using System;
using Datanaut.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Datanaut.Migrations
{
    [DbContext(typeof(DatanautDbContext))]
    partial class DatanautDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Datanaut.Models.Project", b =>
                {
                    b.Property<int>("PkprojectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PKProjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkprojectId"));

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("FkprojectManagerId")
                        .HasColumnType("int")
                        .HasColumnName("FKProjectManagerID");

                    b.Property<DateOnly?>("ProjectEndDate")
                        .HasColumnType("date");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly>("ProjectStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PkprojectId")
                        .HasName("PK__Project__1A1F05A2F3261658");

                    b.HasIndex("FkprojectManagerId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Datanaut.Models.ProjectManager", b =>
                {
                    b.Property<int>("PkprojectManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PKProjectManagerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkprojectManagerId"));

                    b.Property<int>("FkroleId")
                        .HasColumnType("int")
                        .HasColumnName("FKRoleID");

                    b.HasKey("PkprojectManagerId")
                        .HasName("PK__ProjectM__AE6D6ACEB67AB191");

                    b.HasIndex("FkroleId");

                    b.ToTable("ProjectManager");
                });

            modelBuilder.Entity("Datanaut.Models.Report", b =>
                {
                    b.Property<int>("PkreportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PKReportId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkreportId"));

                    b.Property<int>("FkprojectId")
                        .HasColumnType("int")
                        .HasColumnName("FKProjectId");

                    b.Property<DateOnly>("ReportEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ReportStartDate")
                        .HasColumnType("date");

                    b.HasKey("PkreportId")
                        .HasName("PK__Report__BFF8F6AE38A425C4");

                    b.HasIndex(new[] { "FkprojectId", "ReportStartDate", "ReportEndDate" }, "UQ_Report_Project_DateRange")
                        .IsUnique();

                    b.ToTable("Report");
                });

            modelBuilder.Entity("Datanaut.Models.Resource", b =>
                {
                    b.Property<int>("PkresourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PKResourceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkresourceId"));

                    b.Property<int>("FkprojectId")
                        .HasColumnType("int")
                        .HasColumnName("FKProjectID");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PkresourceId")
                        .HasName("PK__Resource__8EF7FE5F3904FD64");

                    b.HasIndex("FkprojectId");

                    b.HasIndex(new[] { "ResourceName", "FkprojectId" }, "UQ_Resources_Name_Project")
                        .IsUnique();

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Datanaut.Models.Role", b =>
                {
                    b.Property<int>("PkroleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PKRoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkroleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PkroleId")
                        .HasName("PK__Role__B962131494311597");

                    b.HasIndex(new[] { "RoleName" }, "UQ_Role_RoleName")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Datanaut.Models.TeamMember", b =>
                {
                    b.Property<int>("PkteamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PKTeamMemberID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkteamMemberId"));

                    b.Property<int>("FkprojectId")
                        .HasColumnType("int")
                        .HasColumnName("FKProjectID");

                    b.Property<int>("FkprojectManagerId")
                        .HasColumnType("int")
                        .HasColumnName("FKProjectManagerID");

                    b.Property<int>("FkroleId")
                        .HasColumnType("int")
                        .HasColumnName("FKRoleID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Skill")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("PkteamMemberId")
                        .HasName("PK__TeamMemb__295C6A18A67427BD");

                    b.HasIndex("FkprojectId");

                    b.HasIndex("FkprojectManagerId");

                    b.HasIndex("FkroleId");

                    b.ToTable("TeamMember");
                });

            modelBuilder.Entity("Datanaut.Models.TimeLog", b =>
                {
                    b.Property<int>("PktimeLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PKTimeLogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PktimeLogId"));

                    b.Property<string>("Activity")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("DateLogged")
                        .HasColumnType("date");

                    b.Property<int>("FkreportId")
                        .HasColumnType("int")
                        .HasColumnName("FKReportID");

                    b.Property<int>("FkteamMemberId")
                        .HasColumnType("int")
                        .HasColumnName("FKTeamMemberID");

                    b.Property<decimal>("TimeWorked")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("PktimeLogId")
                        .HasName("PK__TimeLog__F1CF3406FBCF09AB");

                    b.HasIndex("FkreportId");

                    b.HasIndex("FkteamMemberId");

                    b.ToTable("TimeLog");
                });

            modelBuilder.Entity("Datanaut.Models.Project", b =>
                {
                    b.HasOne("Datanaut.Models.ProjectManager", "FkprojectManager")
                        .WithMany("Projects")
                        .HasForeignKey("FkprojectManagerId")
                        .IsRequired()
                        .HasConstraintName("FK_Project_ProjectManager");

                    b.Navigation("FkprojectManager");
                });

            modelBuilder.Entity("Datanaut.Models.ProjectManager", b =>
                {
                    b.HasOne("Datanaut.Models.Role", "Fkrole")
                        .WithMany("ProjectManagers")
                        .HasForeignKey("FkroleId")
                        .IsRequired()
                        .HasConstraintName("FK_ProjectManager_Role");

                    b.Navigation("Fkrole");
                });

            modelBuilder.Entity("Datanaut.Models.Report", b =>
                {
                    b.HasOne("Datanaut.Models.Project", "Fkproject")
                        .WithMany("Reports")
                        .HasForeignKey("FkprojectId")
                        .IsRequired()
                        .HasConstraintName("FK_Report_Project");

                    b.Navigation("Fkproject");
                });

            modelBuilder.Entity("Datanaut.Models.Resource", b =>
                {
                    b.HasOne("Datanaut.Models.Project", "Fkproject")
                        .WithMany("Resources")
                        .HasForeignKey("FkprojectId")
                        .IsRequired()
                        .HasConstraintName("FK_Resources_Project");

                    b.Navigation("Fkproject");
                });

            modelBuilder.Entity("Datanaut.Models.TeamMember", b =>
                {
                    b.HasOne("Datanaut.Models.Project", "Fkproject")
                        .WithMany("TeamMembers")
                        .HasForeignKey("FkprojectId")
                        .IsRequired()
                        .HasConstraintName("FK_TeamMember_Project");

                    b.HasOne("Datanaut.Models.ProjectManager", "FkprojectManager")
                        .WithMany("TeamMembers")
                        .HasForeignKey("FkprojectManagerId")
                        .IsRequired()
                        .HasConstraintName("FK_TeamMember_ProjectManager");

                    b.HasOne("Datanaut.Models.Role", "Fkrole")
                        .WithMany("TeamMembers")
                        .HasForeignKey("FkroleId")
                        .IsRequired()
                        .HasConstraintName("FK_TeamMember_Role");

                    b.Navigation("Fkproject");

                    b.Navigation("FkprojectManager");

                    b.Navigation("Fkrole");
                });

            modelBuilder.Entity("Datanaut.Models.TimeLog", b =>
                {
                    b.HasOne("Datanaut.Models.Report", "Fkreport")
                        .WithMany("TimeLogs")
                        .HasForeignKey("FkreportId")
                        .IsRequired()
                        .HasConstraintName("FK_TimeLog_Report");

                    b.HasOne("Datanaut.Models.TeamMember", "FkteamMember")
                        .WithMany("TimeLogs")
                        .HasForeignKey("FkteamMemberId")
                        .IsRequired()
                        .HasConstraintName("FK_TimeLog_TeamMember");

                    b.Navigation("Fkreport");

                    b.Navigation("FkteamMember");
                });

            modelBuilder.Entity("Datanaut.Models.Project", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("Resources");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("Datanaut.Models.ProjectManager", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("Datanaut.Models.Report", b =>
                {
                    b.Navigation("TimeLogs");
                });

            modelBuilder.Entity("Datanaut.Models.Role", b =>
                {
                    b.Navigation("ProjectManagers");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("Datanaut.Models.TeamMember", b =>
                {
                    b.Navigation("TimeLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
